name: npm test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
	  registry-url: https://npm.pkg.github.com/kilroy-code
	  scope: '@kilroy-code'
      - run: npm install
      - run: npm test